joint_state_controller:
  type: joint_state_controller/JointStateController
  #publish_rate: 200
  publish_rate: 50

left_wheel_motor_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_leg_to_left_wheel_joint
  required_drive_mode: 3

right_wheel_motor_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_leg_to_right_wheel_joint
  required_drive_mode: 3
