# cf. http://wiki.ros.org/canopen_chain_node#CANopen_Bus_layer
bus:
  device: can0 # socketcan network
  # loopback: false # socket should loop back messages
  # driver_plugin: can::SocketCANInterface
  # master_allocator: canopen::SimpleMaster::Allocator
sync:
  interval_ms: 5 # set to 0 to disable sync
  # update_ms: <interval_ms> #update interval of control loop, must be set explicitly if sync is disabled
  overflow: 0 # overflow sync counter at value or do not set it (0, default)
# heartbeat: # simple heartbeat producer, optional!
# rate: 20 # heartbeat rate
# msg: "77f#05" # message to send, cansend format: heartbeat of node 127 with status 5=Started
