TrajectoryPlannerROS:
   max_vel_x: 1.0
   min_vel_x: 0.01
   max_vel_theta: 0.5
   min_in_place_vel_theta: 0.5
   acc_lim_theta: 1.0
   acc_lim_x: 1.0
   sim_time: 5.0
   heading_lookahead: 0.5
   holonomic_robot: false

DWAPlannerROS:
   max_vel_x: 1.0
   min_vel_x: 0.01
   max_vel_theta: 0.5
   min_in_place_vel_theta: 0.5
   acc_lim_theta: 1.0
   acc_lim_x: 1.0
   sim_time: 5.0
   holonomic_robot: false

TebLocalPlannerROS:
   max_vel_x: 0.5
   min_vel_x: 0.01
   max_vel_theta: 1.0
   acc_lim_theta: 1.0
   acc_lim_x: 0.5
   max_vel_x_backwards: 0.0
   weight_kinematics_forward_drive: 1000.0
   footprint_model:
      type: "circular"
      radius: 0.3
