obstacle_range: 3.0
raytrace_range: 5.0

robot_radius: 0.4

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    sensor_frame: laser
    data_type: LaserScan
    topic: scan_filtered
    marking: true
    clearing: true

inflation_radius: 0.5

map_type: map

track_unknown_space: false
