base_global_planner: "global_planner/GlobalPlanner"
#base_local_planner: "teb_local_planner/TebLocalPlannerROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"
#base_local_planner: "dwa_local_planner/DWAPlannerROS"

controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 3.0
planner_frequency: 0.0
shutdown_costmaps: false
oscillation_timeout: 10.0
oscillation_distance: 0.2
max_planning_retries: 1
recovery_behavior_enabled: false