local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 3.0
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.05
